// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: authentication.proto

#include "authentication.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = ::PROTOBUF_NAMESPACE_ID::internal;
namespace proto {
PROTOBUF_CONSTEXPR AuthenticationRequest::AuthenticationRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.token_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.provider_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_._cached_size_)*/{}} {}
struct AuthenticationRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AuthenticationRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AuthenticationRequestDefaultTypeInternal() {}
  union {
    AuthenticationRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AuthenticationRequestDefaultTypeInternal _AuthenticationRequest_default_instance_;
PROTOBUF_CONSTEXPR AuthenticationResponse::AuthenticationResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.outcome_)*/ 0

  , /*decltype(_impl_.payload_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct AuthenticationResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AuthenticationResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AuthenticationResponseDefaultTypeInternal() {}
  union {
    AuthenticationResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AuthenticationResponseDefaultTypeInternal _AuthenticationResponse_default_instance_;
}  // namespace proto
static ::_pb::Metadata file_level_metadata_authentication_2eproto[2];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_authentication_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_authentication_2eproto = nullptr;
const ::uint32_t TableStruct_authentication_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::proto::AuthenticationRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::proto::AuthenticationRequest, _impl_.token_),
    PROTOBUF_FIELD_OFFSET(::proto::AuthenticationRequest, _impl_.provider_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::proto::AuthenticationResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    PROTOBUF_FIELD_OFFSET(::proto::AuthenticationResponse, _impl_._oneof_case_[0]),
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::proto::AuthenticationResponse, _impl_.outcome_),
    ::_pbi::kInvalidFieldOffsetTag,
    ::_pbi::kInvalidFieldOffsetTag,
    ::_pbi::kInvalidFieldOffsetTag,
    PROTOBUF_FIELD_OFFSET(::proto::AuthenticationResponse, _impl_.payload_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        { 0, -1, -1, sizeof(::proto::AuthenticationRequest)},
        { 10, -1, -1, sizeof(::proto::AuthenticationResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::proto::_AuthenticationRequest_default_instance_._instance,
    &::proto::_AuthenticationResponse_default_instance_._instance,
};
const char descriptor_table_protodef_authentication_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\024authentication.proto\022\005proto\"8\n\025Authent"
    "icationRequest\022\r\n\005token\030\001 \001(\t\022\020\n\010provide"
    "r\030\002 \001(\t\"\323\001\n\026AuthenticationResponse\0226\n\007ou"
    "tcome\030\001 \001(\0162%.proto.AuthenticationRespon"
    "se.Outcome\022\r\n\003url\030\002 \001(\tH\000\022\014\n\002id\030\003 \001(\tH\000\022"
    "\017\n\005error\030\004 \001(\tH\000\"H\n\007Outcome\022\014\n\010REDIRECT\020"
    "\000\022\021\n\rINVALID_TOKEN\020\001\022\021\n\rAUTHENTICATED\020\002\022"
    "\t\n\005ERROR\020\003B\t\n\007payload2e\n\024AuthenticationP"
    "lugin\022M\n\014Authenticate\022\034.proto.Authentica"
    "tionRequest\032\035.proto.AuthenticationRespon"
    "se\"\000B;Z9github.com/scalablepixelstreamin"
    "g/apis/pkg/authenticationb\006proto3"
};
static ::absl::once_flag descriptor_table_authentication_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_authentication_2eproto = {
    false,
    false,
    473,
    descriptor_table_protodef_authentication_2eproto,
    "authentication.proto",
    &descriptor_table_authentication_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_authentication_2eproto::offsets,
    file_level_metadata_authentication_2eproto,
    file_level_enum_descriptors_authentication_2eproto,
    file_level_service_descriptors_authentication_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_authentication_2eproto_getter() {
  return &descriptor_table_authentication_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_authentication_2eproto(&descriptor_table_authentication_2eproto);
namespace proto {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* AuthenticationResponse_Outcome_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_authentication_2eproto);
  return file_level_enum_descriptors_authentication_2eproto[0];
}
bool AuthenticationResponse_Outcome_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr AuthenticationResponse_Outcome AuthenticationResponse::REDIRECT;
constexpr AuthenticationResponse_Outcome AuthenticationResponse::INVALID_TOKEN;
constexpr AuthenticationResponse_Outcome AuthenticationResponse::AUTHENTICATED;
constexpr AuthenticationResponse_Outcome AuthenticationResponse::ERROR;
constexpr AuthenticationResponse_Outcome AuthenticationResponse::Outcome_MIN;
constexpr AuthenticationResponse_Outcome AuthenticationResponse::Outcome_MAX;
constexpr int AuthenticationResponse::Outcome_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class AuthenticationRequest::_Internal {
 public:
};

AuthenticationRequest::AuthenticationRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.AuthenticationRequest)
}
AuthenticationRequest::AuthenticationRequest(const AuthenticationRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  AuthenticationRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.token_) {}

    , decltype(_impl_.provider_) {}

    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.token_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.token_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_token().empty()) {
    _this->_impl_.token_.Set(from._internal_token(), _this->GetArenaForAllocation());
  }
  _impl_.provider_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.provider_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_provider().empty()) {
    _this->_impl_.provider_.Set(from._internal_provider(), _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:proto.AuthenticationRequest)
}

inline void AuthenticationRequest::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.token_) {}

    , decltype(_impl_.provider_) {}

    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.token_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.token_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.provider_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.provider_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

AuthenticationRequest::~AuthenticationRequest() {
  // @@protoc_insertion_point(destructor:proto.AuthenticationRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AuthenticationRequest::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.token_.Destroy();
  _impl_.provider_.Destroy();
}

void AuthenticationRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AuthenticationRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.AuthenticationRequest)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.token_.ClearToEmpty();
  _impl_.provider_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AuthenticationRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string token = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_token();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "proto.AuthenticationRequest.token"));
        } else {
          goto handle_unusual;
        }
        continue;
      // string provider = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_provider();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "proto.AuthenticationRequest.provider"));
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* AuthenticationRequest::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:proto.AuthenticationRequest)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string token = 1;
  if (!this->_internal_token().empty()) {
    const std::string& _s = this->_internal_token();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "proto.AuthenticationRequest.token");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string provider = 2;
  if (!this->_internal_provider().empty()) {
    const std::string& _s = this->_internal_provider();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "proto.AuthenticationRequest.provider");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.AuthenticationRequest)
  return target;
}

::size_t AuthenticationRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.AuthenticationRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string token = 1;
  if (!this->_internal_token().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_token());
  }

  // string provider = 2;
  if (!this->_internal_provider().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_provider());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AuthenticationRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AuthenticationRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AuthenticationRequest::GetClassData() const { return &_class_data_; }


void AuthenticationRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AuthenticationRequest*>(&to_msg);
  auto& from = static_cast<const AuthenticationRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.AuthenticationRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_token().empty()) {
    _this->_internal_set_token(from._internal_token());
  }
  if (!from._internal_provider().empty()) {
    _this->_internal_set_provider(from._internal_provider());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AuthenticationRequest::CopyFrom(const AuthenticationRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.AuthenticationRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AuthenticationRequest::IsInitialized() const {
  return true;
}

void AuthenticationRequest::InternalSwap(AuthenticationRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.token_, lhs_arena,
                                       &other->_impl_.token_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.provider_, lhs_arena,
                                       &other->_impl_.provider_, rhs_arena);
}

::PROTOBUF_NAMESPACE_ID::Metadata AuthenticationRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_authentication_2eproto_getter, &descriptor_table_authentication_2eproto_once,
      file_level_metadata_authentication_2eproto[0]);
}
// ===================================================================

class AuthenticationResponse::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
    PROTOBUF_FIELD_OFFSET(::proto::AuthenticationResponse, _impl_._oneof_case_);
};

AuthenticationResponse::AuthenticationResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.AuthenticationResponse)
}
AuthenticationResponse::AuthenticationResponse(const AuthenticationResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  AuthenticationResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.outcome_) {}

    , decltype(_impl_.payload_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.outcome_ = from._impl_.outcome_;
  clear_has_payload();
  switch (from.payload_case()) {
    case kUrl: {
      _this->_internal_set_url(from._internal_url());
      break;
    }
    case kId: {
      _this->_internal_set_id(from._internal_id());
      break;
    }
    case kError: {
      _this->_internal_set_error(from._internal_error());
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:proto.AuthenticationResponse)
}

inline void AuthenticationResponse::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.outcome_) { 0 }

    , decltype(_impl_.payload_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  clear_has_payload();
}

AuthenticationResponse::~AuthenticationResponse() {
  // @@protoc_insertion_point(destructor:proto.AuthenticationResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AuthenticationResponse::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  if (has_payload()) {
    clear_payload();
  }
}

void AuthenticationResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AuthenticationResponse::clear_payload() {
// @@protoc_insertion_point(one_of_clear_start:proto.AuthenticationResponse)
  switch (payload_case()) {
    case kUrl: {
      _impl_.payload_.url_.Destroy();
      break;
    }
    case kId: {
      _impl_.payload_.id_.Destroy();
      break;
    }
    case kError: {
      _impl_.payload_.error_.Destroy();
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}


void AuthenticationResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.AuthenticationResponse)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.outcome_ = 0;
  clear_payload();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AuthenticationResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .proto.AuthenticationResponse.Outcome outcome = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 8)) {
          ::int32_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
          _internal_set_outcome(static_cast<::proto::AuthenticationResponse_Outcome>(val));
        } else {
          goto handle_unusual;
        }
        continue;
      // string url = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_url();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "proto.AuthenticationResponse.url"));
        } else {
          goto handle_unusual;
        }
        continue;
      // string id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "proto.AuthenticationResponse.id"));
        } else {
          goto handle_unusual;
        }
        continue;
      // string error = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_error();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "proto.AuthenticationResponse.error"));
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* AuthenticationResponse::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:proto.AuthenticationResponse)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .proto.AuthenticationResponse.Outcome outcome = 1;
  if (this->_internal_outcome() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_outcome(), target);
  }

  switch (payload_case()) {
    case kUrl: {
      const std::string& _s = this->_internal_url();
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "proto.AuthenticationResponse.url");
      target = stream->WriteStringMaybeAliased(2, _s, target);
      break;
    }
    case kId: {
      const std::string& _s = this->_internal_id();
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "proto.AuthenticationResponse.id");
      target = stream->WriteStringMaybeAliased(3, _s, target);
      break;
    }
    case kError: {
      const std::string& _s = this->_internal_error();
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "proto.AuthenticationResponse.error");
      target = stream->WriteStringMaybeAliased(4, _s, target);
      break;
    }
    default: ;
  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.AuthenticationResponse)
  return target;
}

::size_t AuthenticationResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.AuthenticationResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .proto.AuthenticationResponse.Outcome outcome = 1;
  if (this->_internal_outcome() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_outcome());
  }

  switch (payload_case()) {
    // string url = 2;
    case kUrl: {
      total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                      this->_internal_url());
      break;
    }
    // string id = 3;
    case kId: {
      total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                      this->_internal_id());
      break;
    }
    // string error = 4;
    case kError: {
      total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                      this->_internal_error());
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AuthenticationResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AuthenticationResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AuthenticationResponse::GetClassData() const { return &_class_data_; }


void AuthenticationResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AuthenticationResponse*>(&to_msg);
  auto& from = static_cast<const AuthenticationResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.AuthenticationResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_outcome() != 0) {
    _this->_internal_set_outcome(from._internal_outcome());
  }
  switch (from.payload_case()) {
    case kUrl: {
      _this->_internal_set_url(from._internal_url());
      break;
    }
    case kId: {
      _this->_internal_set_id(from._internal_id());
      break;
    }
    case kError: {
      _this->_internal_set_error(from._internal_error());
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AuthenticationResponse::CopyFrom(const AuthenticationResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.AuthenticationResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AuthenticationResponse::IsInitialized() const {
  return true;
}

void AuthenticationResponse::InternalSwap(AuthenticationResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.outcome_, other->_impl_.outcome_);
  swap(_impl_.payload_, other->_impl_.payload_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata AuthenticationResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_authentication_2eproto_getter, &descriptor_table_authentication_2eproto_once,
      file_level_metadata_authentication_2eproto[1]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::proto::AuthenticationRequest*
Arena::CreateMaybeMessage< ::proto::AuthenticationRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::proto::AuthenticationRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::proto::AuthenticationResponse*
Arena::CreateMaybeMessage< ::proto::AuthenticationResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::proto::AuthenticationResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
